### ISSUE TITLE
Undefined methods in main.go

### ISSUE THREAD

**Issue by mcolburn** [blevesearch/beer-search#10]
Running main.go results in three errors:

```
./main.go:57:24: undefined: buildIndexMapping
./main.go:89:12: undefined: staticFileRouter
./main.go:99:29: undefined: docIDLookup
```

Is the problem because the functions are not exported by mapping.go and http_util.go?

**Comment by mschoch** [comment]
The functions do not need to be exported because they are used by the same package (main) where they are defined.  The application builds fine:

```
$ git clone git@github.com:blevesearch/beer-search.git
Cloning into 'beer-search'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7463 (delta 1), reused 3 (delta 1), pack-reused 7459
Receiving objects: 100% (7463/7463), 2.12 MiB | 25.28 MiB/s, done.
Resolving deltas: 100% (2902/2902), done.
$ cd beer-search 
$ ls
data  go.mod  go.sum  http_util.go  main.go  main_test.go  mapping_example1.go  mapping_example2.go  mapping.go  README.md  static
$ go build
$ ./beer-search 
2020/10/05 11:47:25 GOMAXPROCS: 32
2020/10/05 11:47:25 Creating new index...
2020/10/05 11:47:25 Listening on :8094
2020/10/05 11:47:25 Indexing...
2020/10/05 11:47:26 Indexed 1000 documents, in 1.08s (average 1.08ms/doc)
^C
```

It appears maybe you are attempting to simply run the main.go, but that is not supported:
```
$ go run main.go
# command-line-arguments
./main.go:57:24: undefined: buildIndexMapping
./main.go:89:12: undefined: staticFileRouter
./main.go:99:29: undefined: docIDLookup
```

**Comment by mcolburn** [comment]
If running main.go is not supported, then how is it supposed to be run?

**Comment by mcolburn** [comment]
Thank you for your prompt reply! 

```
go build
```

does work fine.

Might I suggest then, that you update the README to indicate that this example is meant to be built and then run from the executable?

**Comment by mschoch** [comment]
Can you help me understand why you expected `go run main.go` to work?  In my experience that never works for real applications, as they typically grow beyond a single file, and typing `go run file1.go file2.go file3.go etc` becomes unwieldy.

**Comment by mcolburn** [comment]
Personally, I am unfamiliar with go applications that can't be run from main.go, although I have only been using go for about a year.   

As an example, the application I am currently working on (Doxa) has over 100 go files: https://gitlab.com/ocmc/liturgiko/doxa <https://gitlab.com/ocmc/liturgiko/doxa>

The main.go in cmd/doxago starts the application.  The various go files are imported.

I am simply suggesting that you update the README to tell people it needs to be run by building it first.

Thank you!

**Comment by mschoch** [comment]
That would not be accurate either, it does work using `go run`, you just have to use it correctly:

```
$ go run main.go http_util.go mapping.go
2020/10/05 12:14:56 GOMAXPROCS: 32
2020/10/05 12:14:56 Opening existing index...
2020/10/05 12:14:56 Listening on :8094
^Csignal: interrupt
```

When using `go run` you have supply all the required file names.

**Comment by mcolburn** [comment]
Then, may I suggest you update the README to indicate the two ways in which it can be run?  Now that I have it working, I can see that it is a fantastic example.  It would be a shame for go newbies such as myself to not understand how to run it.  Again, thank you for taking time to respond!
